app:
  message: ${HW_MESSAGE:"hello world"}

server:
  port: ${HW_SERVER_PORT:8080}
  shutdown: graceful

logging:
  level:
    org:
      springframework:
        context:       ${HW_LOGGING_LEVEL_SPRING_CONTEXT:WARN}
        web:           ${HW_LOGGING_LEVEL_SPRING_WEB:WARN}
    root: ${HW_ROOT_LOGGING_LEVEL:INFO}
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"thread\": \"%thread\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\\\n'}\"}%n"

spring:
  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIME:1m}
  main:
    banner-mode: off
  profiles:
    active: default
